defmodule UwBilling.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :api_key, :text, null: false
      add :stripe_customer_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:api_key], name: "users_unique_api_key_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_subscription_id, :text
      add :stripe_customer_id, :text
      add :current_period_start, :utc_datetime
      add :current_period_end, :utc_datetime
      add :trial_end, :utc_datetime
      add :cancel_at_period_end, :boolean, default: false
      add :past_due_since, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "free"

      add :user_id,
          references(:users,
            column: :id,
            name: "subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :plan_id, :uuid, null: false
      add :scheduled_plan_id, :uuid
    end

    create index(:subscriptions, [:status],
             name: "subscriptions_billable_status_idx",
             where: "status IN ('active', 'past_due', 'trialing')"
           )

    create index(:subscriptions, [:user_id],
             name: "subscriptions_active_user_idx",
             where: "status != 'canceled'"
           )

    create table(:stripe_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_event_id, :text, null: false
      add :event_type, :text, null: false
      add :payload, :map, null: false
      add :processed_at, :utc_datetime
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stripe_events, [:stripe_event_id],
             name: "stripe_events_unique_event_index"
           )

    create table(:stripe_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton_key, :text, null: false, default: "default"
      add :secret_key, :text, null: false
      add :webhook_secret, :text, null: false
      add :price_id_pro, :text, null: false
      add :price_id_premium, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :verified_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stripe_configs, [:singleton_key], name: "stripe_configs_singleton_index")

    create table(:plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:subscriptions) do
      modify :plan_id,
             references(:plans,
               column: :id,
               name: "subscriptions_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :scheduled_plan_id,
             references(:plans,
               column: :id,
               name: "subscriptions_scheduled_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:subscriptions, [:stripe_subscription_id],
             name: "subscriptions_unique_stripe_subscription_index"
           )

    alter table(:plans) do
      add :name, :text, null: false
      add :tier, :text, null: false
      add :stripe_price_id, :text
      add :amount_cents, :bigint, null: false, default: 0
      add :interval, :text
      add :api_request_limit, :bigint
      add :features, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:plans, [:stripe_price_id], name: "plans_unique_stripe_price_index")

    create table(:invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_invoice_id, :text, null: false
      add :amount_cents, :bigint, null: false
      add :status, :text, null: false
      add :due_date, :date
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "invoices_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:invoices, [:stripe_invoice_id],
             name: "invoices_unique_stripe_invoice_index"
           )

    create table(:congress_trades, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :trader_name, :text, null: false
      add :ticker, :text, null: false
      add :transaction_type, :text, null: false
      add :amount_range, :text
      add :filed_at, :date
      add :traded_at, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:congress_trades, [:trader_name, :ticker, :traded_at, :transaction_type],
             name: "congress_trades_unique_disclosure_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :congress_trades,
                     [:trader_name, :ticker, :traded_at, :transaction_type],
                     name: "congress_trades_unique_disclosure_index"
                   )

    drop table(:congress_trades)

    drop_if_exists unique_index(:invoices, [:stripe_invoice_id],
                     name: "invoices_unique_stripe_invoice_index"
                   )

    drop constraint(:invoices, "invoices_subscription_id_fkey")

    drop table(:invoices)

    drop_if_exists unique_index(:plans, [:stripe_price_id],
                     name: "plans_unique_stripe_price_index"
                   )

    alter table(:plans) do
      remove :updated_at
      remove :inserted_at
      remove :features
      remove :api_request_limit
      remove :interval
      remove :amount_cents
      remove :stripe_price_id
      remove :tier
      remove :name
    end

    drop_if_exists unique_index(:subscriptions, [:stripe_subscription_id],
                     name: "subscriptions_unique_stripe_subscription_index"
                   )

    drop constraint(:subscriptions, "subscriptions_plan_id_fkey")

    drop constraint(:subscriptions, "subscriptions_scheduled_plan_id_fkey")

    alter table(:subscriptions) do
      modify :scheduled_plan_id, :uuid
      modify :plan_id, :uuid
    end

    drop table(:plans)

    drop_if_exists unique_index(:stripe_configs, [:singleton_key],
                     name: "stripe_configs_singleton_index"
                   )

    drop table(:stripe_configs)

    drop_if_exists unique_index(:stripe_events, [:stripe_event_id],
                     name: "stripe_events_unique_event_index"
                   )

    drop table(:stripe_events)

    drop constraint(:subscriptions, "subscriptions_user_id_fkey")

    drop_if_exists index(:subscriptions, [:user_id], name: "subscriptions_active_user_idx")

    drop_if_exists index(:subscriptions, [:status], name: "subscriptions_billable_status_idx")

    drop table(:subscriptions)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:api_key], name: "users_unique_api_key_index")

    drop table(:users)
  end
end
